### ISSUE TITLE
Usage of your package in mine

### ISSUE THREAD

**Issue by dixonwille** [daviddengcn/go-colortext#4]
I have a package that I feel is quite useful. I am using the MIT License and added a link to this repo in the Readme (before reading your license sorry). I would like to continue using this package as it is a great tool to use for cross platform applications (I couldn't find another color tool that was as simple as this and cross platform). If there are any concerns or problems with this please contact me.

Thanks,
Will Dixon

**Comment by daviddengcn** [comment]
I just added MIT license as well for your convenience.
